

#spring:
#  profiles:
#    active:
spring:
  application:
    name: user-service

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

#spring:
#  profiles: node-two
#  application:
#    name: user-service
#
#server:
#  port: 8081
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8001/eureka




